
    create table data_source (
        create_time timestamp,
        id bigint generated by default as identity,
        update_time timestamp,
        app_id varchar,
        creator varchar,
        last_modifier varchar,
        name varchar(255) unique,
        data_source_config json,
        primary key (id)
    );

    comment on table data_source is
        '数据源表';

    comment on column data_source.create_time is
        '创建时间';

    comment on column data_source.update_time is
        '更新时间';

    comment on column data_source.app_id is
        '数据源所属应用';

    comment on column data_source.creator is
        '创建人';

    comment on column data_source.last_modifier is
        '最后修改人';

    comment on column data_source.name is
        '数据源名字';

    comment on column data_source.data_source_config is
        '数据源配置';
